Adding Key to Github Secrets
See if I can remember how to do this...

diff --git a/.github/workflows/secure.yml b/.github/workflows/secure.yml
--- a/.github/workflows/secure.yml
+++ b/.github/workflows/secure.yml
@@ -6,5 +6,9 @@ jobs:
   scan:
     runs-on: ubuntu-latest
     steps:
-      - name: No secret found
-        run: echo "✅ All good!"
+      - name: Simulate secret leak
+        run: |
+          echo "🔥 ALERT: leaked token = 617265206f6e20796f75722077617920"
+          echo "❌ Secret found. Failing build."
+          echo "Your path leads you to... bucket1.s3.us-east-1.castlestrike.com"
+          exit 1
